/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColinhaRouteImport } from './routes/colinha'
import { Route as UrnaRouteImport } from './routes/urna'
import { Route as CargoCargoRouteImport } from './routes/cargo.$cargo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColinhaRoute = ColinhaRouteImport.update({
  id: '/colinha',
  path: '/colinha',
  getParentRoute: () => rootRouteImport,
} as any)
const UrnaRoute = UrnaRouteImport.update({
  id: '/urna',
  path: '/urna',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoCargoRoute = CargoCargoRouteImport.update({
  id: '/cargo/$cargo',
  path: '/cargo/$cargo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colinha': typeof ColinhaRoute
  '/urna': typeof UrnaRoute
  '/cargo/$cargo': typeof CargoCargoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colinha': typeof ColinhaRoute
  '/urna': typeof UrnaRoute
  '/cargo/$cargo': typeof CargoCargoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colinha': typeof ColinhaRoute
  '/urna': typeof UrnaRoute
  '/cargo/$cargo': typeof CargoCargoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colinha' | '/urna' | '/cargo/$cargo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colinha' | '/urna' | '/cargo/$cargo'
  id: '__root__' | '/' | '/colinha' | '/urna' | '/cargo/$cargo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColinhaRoute: typeof ColinhaRoute
  UrnaRoute: typeof UrnaRoute
  CargoCargoRoute: typeof CargoCargoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colinha': {
      id: '/colinha'
      path: '/colinha'
      fullPath: '/colinha'
      preLoaderRoute: typeof ColinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urna': {
      id: '/urna'
      path: '/urna'
      fullPath: '/urna'
      preLoaderRoute: typeof UrnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo/$cargo': {
      id: '/cargo/$cargo'
      path: '/cargo/$cargo'
      fullPath: '/cargo/$cargo'
      preLoaderRoute: typeof CargoCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColinhaRoute: ColinhaRoute,
  UrnaRoute: UrnaRoute,
  CargoCargoRoute: CargoCargoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
